In [85]:
import pandas as pd
import numpy as np

from pandas import DataFrame
from pandas import Series

import json

<h1 style ="color:blue">Data Loading and Parsing</h2>

<div style = "color:green; background-color:lightblue">Data loading referes to reading and accessing data from various file formats. The process of retrieving data or loading data into tabular form is called parsing.</div>

<h2 style = "color:blue">CSV Files</h2>

<div style = "color:green; background-color:lightblue">CSV file stores values, in which each values are seperated by comman or other delimiters(|,;). Pandas provides various functionalities to convert csv file to data frame which is powerful structure for data manipulation and analysis.

<h3 style="color:blue">Reading CSV Files</h3>

In [82]:
df = pd.read_csv('/home/kartika/Downloads/people_data.csv')
df
#pd.set_option('display.max_rows',None) To avoid .... and display all rows

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [30]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Shelby                2 non-null      object
 1   Terrell               2 non-null      object
 2   Male                  2 non-null      object
 3   elijah57@example.net  2 non-null      object
 4   1945-10-26            2 non-null      object
 5   Games developer       2 non-null      object
dtypes: object(6)
memory usage: 228.0+ bytes

,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
count,2,2,2,2,2,2
unique,2,2,1,2,2,2
top,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
freq,1,1,2,1,1,1

In [7]:
df = pd.read_csv('/home/kartika/Downloads/people_data.csv', usecols = [ 'First Name','Email'])
df

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

<div style = "color:green; background-color:lightblue">usecols parameter can be used to load only selected columns from the file.

In [12]:
df = pd.read_csv('/home/kartika/Downloads/people_data.csv', index_col = ['First Name','Last Name'])
df

,,Sex,Email,Date of birth,Job Title
First Name,Last Name,,,,
Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

<div style = "color:green; background-color:lightblue"> index_col parameter can be used to set one or more column as data frame index for easier referencing.

In [13]:
df = pd.read_csv('/home/kartika/Downloads/people_data.csv', header = 1)
df

,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
0,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
1,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
2,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
3,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

<div style = "color:green; background-color:lightblue">Similarly header parameter can be used to set any of the row as data frame header.

In [26]:
df = pd.read_csv('/home/kartika/Downloads/people_data.csv', sep = ',')
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

<div style = "background-color:lightblue; color:green">sep parameters tells pandas how data is structured in file ( how columns are seperated). Using wrong sep value shows all column in single line.

In [27]:
df = pd.read_csv('/home/kartika/Downloads/people_data.csv', nrows = 3)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

<div style = "background-color:lightblue; color:green">nrows parameters limits the numbers of rows to be displayed.

In [28]:
df = pd.read_csv('/home/kartika/Downloads/people_data.csv', skiprows = [0,2,3])
df

,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
0,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
1,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

<div style = "background-color:lightblue; color:green"> skiprows parameters skip particular rows from the data.

<h3 style = "color:blue">Writing to CSV Files</h3>

In [35]:
obj = DataFrame(np.random.randint(1,100, size = (4,5)), index = list('abcd'), columns = ['First','Second','Third','Fourth','Fifth'])

   First  Second  Third  Fourth  Fifth
a     65      15     75      47     74
b     31      93     16      41     46
c     48      73     78      87     97
d      4      71      8      39      3

In [53]:
obj.to_csv('/home/kartika/Downloads/convertingdftocsv.csv')

In [55]:
df1 = pd.read_csv('/home/kartika/Downloads/convertingdftocsv.csv', index_col = 0)
df1

   First  Second  Third  Fourth  Fifth
a     65      15     75      47     74
b     31      93     16      41     46
c     48      73     78      87     97
d      4      71      8      39      3

In [69]:
obj2 = DataFrame(np.random.randint(1,100, size = (4,4)), index = list('abcd'), columns = ['First','Second','Third','Fourth'])
obj2.to_csv('/home/kartika/Downloads/convertingdftocsv2.csv', sep = "|", index = False)

In [71]:
df2 = pd.read_csv('/home/kartika/Downloads/convertingdftocsv2.csv', sep = "|")
print(df2)

   First  Second  Third  Fourth
0     91      44     31      61
1     65      74     68       3
2     71      63     60       5
3     19      60     81      14

<div style = "background-color:lightblue; color:green">Here internally the values in dataset is seperated by "|".

In [74]:
obj2.to_csv('/home/kartika/Downloads/convertingdftocsv2.csv', columns = ['First'])
df2 = pd.read_csv('/home/kartika/Downloads/convertingdftocsv2.csv')
df2

  Unnamed: 0  First
0          a     91
1          b     65
2          c     71
3          d     19

<div style = "background-color:lightblue; color:green">We can also write particular column from dataframe to csv.

<h2 style = "color:blue">Reading JSON File</h2>

<div style = "background-color:lightblue; color:green">JSON ( Java-Script Object Notation) stores data in key-values format like python. There are mainly three methods to read json file.

In [84]:
df1 = pd.read_json('/home/kartika/Downloads/weather.json')
df1.head(5)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30,SW,NW,6,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39,E,W,4,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85,N,NNE,6,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54,WNW,W,30,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50,SSE,ESE,20,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

<div style = "background-color:lightblue; color:green">pd.read_json helps to directly json file into pandas dataframe.

In [89]:
json_data = [
    {'id':1,'Name':'Alpha'},
    {'id':2, 'Name':'Beta'},
    {'id':3, 'Name':'Gamma'},
    {'id':4, 'Name':'Theta'}
]
content = json.dumps(json_data)
with open('/home/kartika/Downloads/selfcreatedjsonfile.json','w') as f:
    f.write(content)

In [90]:
with open('/home/kartika/Downloads/selfcreatedjsonfile.json','r') as f:
    data = f.read()
content = json.loads(data)

In [93]:
content

[{'id': 1, 'Name': 'Alpha'},
 {'id': 2, 'Name': 'Beta'},
 {'id': 3, 'Name': 'Gamma'},
 {'id': 4, 'Name': 'Theta'}]

<div style = "background-color:lightblue; color:green"> Another method of reading json file is by using json module. json.jumps converts python data (list of dictionary) to json format. json.loads converts json data to python data format.

In [94]:
dff = DataFrame(content)
dff

   id   Name
0   1  Alpha
1   2   Beta
2   3  Gamma
3   4  Theta

<div style = "background-color:lightblue; color:green">If data stored in json file as dictionary then it can be directly converted to DataFrame using DataFrame function.


<h2 style = "color:blue"> Reading Excel File</h2>

In [100]:
dfff = pd.read_excel('/home/kartika/Downloads/Computer_Sales.xlsx')
print(dfff)

    Brand      Jan      Feb      Mar      Apr      May      Jun      Jul  \
0    Dell  12000.0  13500.0  11000.0  15000.0  17500.0  19000.0  21000.0
1      HP  14000.0  15000.0  13000.0  16000.0  18000.0  20000.0  22000.0
2  Lenovo  11000.0  12000.0  10000.0  14000.0  15500.0  17000.0  18000.0
3    Asus  10000.0  11500.0  10500.0  13000.0  14500.0  16000.0  16500.0
4    Acer   9000.0  10000.0   9500.0  12000.0  13500.0  15000.0  15500.0
5   Apple  20000.0  21000.0  19500.0  23000.0  25000.0  27000.0  29000.0
6     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

       Aug      Sep      Oct      Nov      Dec    Total   Percent
0  20500.0  18000.0  16000.0  15500.0  17000.0   196000  0.163948
1  21000.0  19000.0  16500.0  16000.0  17500.0   208000  0.173986
2  18500.0  17000.0  15000.0  14500.0  16000.0   178500  0.149310
3  17000.0  15500.0  14000.0  13500.0  15000.0   167000  0.139691
4  16000.0  14500.0  13000.0  12500.0  14000.0   154500  0.129235
5  28500.0  26000.0  24000.0  23500.0  25000.0   291500  0.243831
6      NaN      NaN      NaN      NaN      NaN  1195500       NaN

<div style = "background-color:lightblue; color:green"> IF there are multiple sheets in the excel file then the above command will only prompt the first sheet. To use all the sheets from the excel file into data frame below method can be used.

In [104]:
# File = "/home/kartika/Downloads/Computer_Sales.xlsx"
# Sheet1 = pd.read_excel(File, sheet_name = 0, index_col = None)
# Sheet2 = pd.read_excel(File, sheet_name = 1, index_col = None)
# dfff = pd.concat([Sheet1, Sheet2])
# dfff

<h2 style = "color:blue">Reading Text File</h2>

In [106]:
dfff = pd.read_csv('/home/kartika/Documents/text.txt', sep = ' ')
dfff

    Name  Code
0  Alpha   434
1   Beta   423
2  Gamma   425
3  Delta   421
4  Theta   690